server:
  port: 8080

com:
  ugrong:
    dingtalk:
      enabled: true
      url: 'https://oapi.dingtalk.com'
      robots:
        robot1:
          access-token: 'accessToken1'
          enable-sign: true
          secret: 'secret1'
        robot2:
          access-token: 'accessToken2'
          enable-sign: true
          secret: 'secret2'

logging:
  level:
    org:
      springframework:
        web: debug
